from .habitat import ITerrestrial
from .habitat import IAquatic
from .animal import IFreshwater
from .animal import ISaltwater
from .animal import IFlying
from .animal import IWalking
from .animal import ISwimming
from .identifiable import Identifiable
from .habitat import IContainsAnimals
from .habitat import IContainsPlants
