from .terrestrial import ITerrestrial
from .aquatic import IAquatic
from .animal import IFreshwater
from .animal import ISaltwater
from .animal import IFreshSaltWater
from .animal import IFlying
from .animal import IWalking
from .animal import ISwimming
from .identifiable import Identifiable
from .habitat import IContainsAnimals
from .habitat import IContainsPlants
from .plant import ISeedProducing
from .drought_tolerant import IDroughtTolerant
